server:
  port: 9888
  context-path: /blog

spring:
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
  # 默认值为 /**
    mvc:
      static-path-pattern: /**
  # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    resources:
      static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  datasource:
#  192.168.31.37
    url: jdbc:mysql://39.106.149.250:3306/sys_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhangzhe1518
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

  redis:
    host: 39.106.149.250
    database: 0
    port: 6379
    password: zhangzhe1518
    jedis:
      pool:
        max-active: 10
        max-wait: 1
        max-idle: 8
    timeout: 10000



mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: com.alex.entity
  #控制台打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

